apiVersion: v1
kind: ConfigMap
metadata:
  name: iibmq-config
  namespace: ibmpoc
data:
  LICENSE: "accept"
  NODENAME: "MYNODE"
  SERVERNAME: "MYSERVER"

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: iibmq-deployment
  namespace: ibmpoc
  labels:
    app: iibmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iibmq
  template:
    metadata:
      labels:
        app: iibmq
    spec:
      imagePullSecrets:
        - name: external-registry
      containers:
      - name: iibmq
        image: fxnaranjom/pocibmiib:1
        env:
          - name: LICENSE
            valueFrom:
              configMapKeyRef:
                name: iibmq-config
                key: LICENSE
          - name: NODENAME
            valueFrom:
              configMapKeyRef:
                name: iibmq-config
                key: NODENAME
          - name: SERVERNAME
            valueFrom:
              configMapKeyRef:
                name: iibmq-config
                key: SERVERNAME
        imagePullPolicy: Always
        ports:
        - containerPort: 4414
          name: console
        - containerPort: 7800
          name: http
        resources:
          requests:
            memory: "500Mi"
            cpu: "400m"
          limits:
            memory: "700Mi"
            cpu: "1000m"

---

apiVersion: v1
kind: Service
metadata:
  name: iibmq
spec:
  selector:
    app: iibmq
  ports:
  - protocol: TCP
    port: 4414
    name: console
  - protocol: TCP
    port: 7800
    name: http

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: iibmq-console
  namespace: ibmpoc
spec:
  to:
    kind: Service
    name: iibmq
    weight: 100
  port:
    targetPort: console
  wildcardPolicy: None

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: iibmq-http
  namespace: ibmpoc
spec:
  to:
    kind: Service
    name: iibmq
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None