apiVersion: v1
kind: ConfigMap
metadata:
  name: ace-config
  namespace: ibmpoc
data:
  LICENSE: "accept"
  ACE_SERVER_NAME: "MYSERVER"
  ACE_ENABLE_METRICS: "true"

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-deployment
  namespace: ibmpoc
  labels:
    app: ace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace
  template:
    metadata:
      labels:
        app: ace
    spec:
      imagePullSecrets:
        - name: external-registry
      containers:
      - name: ace
        image: us.icr.io/pocbp/ace:1
        env:
          - name: LICENSE
            valueFrom:
              configMapKeyRef:
                name: ace-config
                key: LICENSE
          - name: ACE_SERVER_NAME
            valueFrom:
              configMapKeyRef:
                name: ace-config
                key: ACE_SERVER_NAME
          - name: ACE_ENABLE_METRICS
            valueFrom:
              configMapKeyRef:
                name: ace-config
                key: ACE_ENABLE_METRICS
        imagePullPolicy: Always
        ports:
        - containerPort: 7600
          name: console
        - containerPort: 7800
          name: http
        resources:
          requests:
            memory: "500Mi"
            cpu: "400m"
          limits:
            memory: "700Mi"
            cpu: "1000m"

---

apiVersion: v1
kind: Service
metadata:
  name: ace
spec:
  selector:
    app: ace
  ports:
  - protocol: TCP
    port: 7600
    name: console
  - protocol: TCP
    port: 7800
    name: http

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ace-console
  namespace: ibmpoc
spec:
  to:
    kind: Service
    name: ace
    weight: 100
  port:
    targetPort: console
  wildcardPolicy: None

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ace-http
  namespace: ibmpoc
spec:
  to:
    kind: Service
    name: ace
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None