apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  imagePullSecrets:
    - name: external-registry
  containers:
  - name: myapp-container
    image: us.icr.io/pocbp/nginx:1
