apiVersion: v1
kind: ConfigMap
metadata:
  name: acemq-config
  namespacemq: ibmpoc
data:
  LICENSE: "accept"
  ACE_SERVER_NAME: "ACESERVER"
  MQ_QMGR_NAME: "QMGR"
  ACE_ENABLE_METRICS: "true"

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: acemq-deployment
  namespacemq: ibmpoc
  labels:
    app: acemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acemq
  template:
    metadata:
      labels:
        app: acemq
    spec:
      imagePullSecrets:
        - name: external-registry
      containers:
      - name: acemq
        image: fxnaranjom/pocibmace:1
        env:
          - name: LICENSE
            valueFrom:
              configMapKeyRef:
                name: acemq-config
                key: LICENSE
          - name: ACE_SERVER_NAME
            valueFrom:
              configMapKeyRef:
                name: acemq-config
                key: ACE_SERVER_NAME
          - name: ACE_ENABLE_METRICS
            valueFrom:
              configMapKeyRef:
                name: acemq-config
                key: ACE_ENABLE_METRICS
          - name: MQ_QMGR_NAME
            valueFrom:
              configMapKeyRef:
                name: acemq-config
                key: MQ_QMGR_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 7600
          name: console
        - containerPort: 7800
          name: http
        - containerPort: 9443
          name: mqconsole
        resources:
          requests:
            memory: "500Mi"
            cpu: "400m"
          limits:
            memory: "700Mi"
            cpu: "1000m"

---

apiVersion: v1
kind: Service
metadata:
  name: acemq
spec:
  selector:
    app: acemq
  ports:
  - protocol: TCP
    port: 7600
    name: console
  - protocol: TCP
    port: 7800
    name: http
  - protocol: TCP
    port: 9443
    name: mqconsole

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: acemq-console
  namespacemq: ibmpoc
spec:
  to:
    kind: Service
    name: acemq
    weight: 100
  port:
    targetPort: console
  wildcardPolicy: None

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: acemq-http
  namespacemq: ibmpoc
spec:
  to:
    kind: Service
    name: acemq
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqconsoleace
  namespace: ibmpoc
spec:
  to:
    kind: Service
    name: acemq
    weight: 100
  port:
    targetPort: mqconsole
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None