apiVersion: v1
kind: ConfigMap
metadata:
  name: acemq-config
  namespacemq: ibmpoc
data:
  LICENSE: "accept"
  ACE_SERVER_NAME: "ACESERVER"
  MQ_QMGR_NAME: "QMGR"
  ACE_ENABLE_METRICS: "true"
  ACE_TRUSTSTORE_PASSWORD: "020kw30"
  ACE_KEYSTORE_PASSWORD: "020kw30"


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ace-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs02
  nfs:
    path: /nfs/IntegrationBus/
    server: 10.50.8.114

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: ace-pv2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs03
  nfs:
    path: /nfs/Traces/
    server: 10.50.8.114

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: ace-pv3
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs04
  nfs:
    path: /nfs/home/aceuser/initial-config
    server: 10.50.8.114

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs02

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-pvc2
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs03

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-pvc3
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs04
  

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: acemq-deployment
  namespacemq: ibmpoc
  labels:
    app: acemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acemq
  template:
    metadata:
      labels:
        app: acemq
    spec:
      imagePullSecrets:
        - name: external-registry
      volumes:
        - name: ace
          persistentVolumeClaim:
            claimName: ace-pvc
        - name: ace2
          persistentVolumeClaim:
            claimName: ace-pvc2
        - name: ace3
          persistentVolumeClaim:
            claimName: ace-pvc3
      containers:
      - name: acemq
        image: fxnaranjom/pocibmace:1
        volumeMounts:
        - mountPath: "/etc/IntegrationBus/"
          name: ace
        - mountPath: "/Traces/"
          name: ace2
        - mountPath: "/home/aceuser/initial-config"
          name: ace3
        env:
          - name: LICENSE
            valueFrom:
              configMapKeyRef:
                name: acemq-config
                key: LICENSE
          - name: ACE_SERVER_NAME
            valueFrom:
              configMapKeyRef:
                name: acemq-config
                key: ACE_SERVER_NAME
          - name: ACE_ENABLE_METRICS
            valueFrom:
              configMapKeyRef:
                name: acemq-config
                key: ACE_ENABLE_METRICS
          - name: MQ_QMGR_NAME
            valueFrom:
              configMapKeyRef:
                name: acemq-config
                key: MQ_QMGR_NAME
          - name: ACE_TRUSTSTORE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: acemq-config
                key: ACE_TRUSTSTORE_PASSWORD
          - name: ACE_KEYSTORE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: acemq-config
                key: ACE_KEYSTORE_PASSWORD
        imagePullPolicy: Always
        ports:
        - containerPort: 7600
          name: console
        - containerPort: 7800
          name: http
        - containerPort: 9443
          name: mqconsole
        resources:
          requests:
            memory: "500Mi"
            cpu: "400m"
          limits:
            memory: "700Mi"
            cpu: "1000m"

---

apiVersion: v1
kind: Service
metadata:
  name: acemq
spec:
  selector:
    app: acemq
  ports:
  - protocol: TCP
    port: 7600
    name: console
  - protocol: TCP
    port: 7800
    name: http
  - protocol: TCP
    port: 9443
    name: mqconsole

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: acemq-console
  namespacemq: ibmpoc
spec:
  to:
    kind: Service
    name: acemq
    weight: 100
  port:
    targetPort: console
  wildcardPolicy: None

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: acemq-http
  namespacemq: ibmpoc
spec:
  to:
    kind: Service
    name: acemq
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None


---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mqconsoleace
  namespace: ibmpoc
spec:
  to:
    kind: Service
    name: acemq
    weight: 100
  port:
    targetPort: mqconsole
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None